#![feature(thin_box)]
#![feature(box_vec_non_null)]
#![feature(mapped_lock_guards)]
#![feature(str_as_str)]
#![feature(allocator_api)]
#![feature(layout_for_ptr)]
#![feature(const_trait_impl)]
#![feature(const_default)]
#![feature(const_try)]
#![feature(current_thread_id)]
#![feature(likely_unlikely)]
#![feature(generic_atomic)]
#![feature(associated_type_defaults)]
#![feature(decl_macro)]
#![feature(ptr_internals)]
#![feature(box_as_ptr)]
#![feature(const_convert)]
#![feature(const_clone)]
#![feature(const_destruct)]
#![feature(alloc_layout_extra)]
#![feature(clone_from_ref)]
#![feature(core_intrinsics)]
#![feature(ptr_alignment_type)]
#![feature(cfg_select)]
#![feature(slice_ptr_get)]
#![feature(specialization)]
#![feature(lock_value_accessors)]
#![feature(const_option_ops)]
#![feature(const_cmp)]
#![feature(super_let)]
#![feature(const_cell_traits)]
#![feature(contracts)]
#![feature(const_eval_select)]
#![feature(ptr_as_ref_unchecked)]
#![feature(ptr_as_uninit)]
//
#![allow(static_mut_refs)]
#![allow(internal_features, incomplete_features)]
#![allow(clippy::mut_from_ref)]
#![allow(clippy::get_first)]
#![allow(clippy::new_without_default)]

pub mod memory;
pub mod stdlib;
#[cfg(test)]
pub mod test_utils;
pub mod type_system;
pub mod value;
pub mod virtual_machine;
